routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;
use Intervention\Image\ImageManagerStatic as Image;

//Authentication
Route::get('/iniciar-sesion', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('/iniciar-sesion', 'Auth\LoginController@login');

// Registration
Route::get('/registro', 'Auth\RegisterController@showRegistrationForm')->name('register');
Route::post('/registro', 'Auth\RegisterController@register');

Route::get('/salir', 'Auth\LoginController@logout')->name('logout');

//Reset password
Route::get('recuperar-clave', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('recuperar-clave', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset')->name('password.update');

//User authenticated
Route::group(['middleware' => ['auth']], function () { 

    Route::group(['middleware' => ['userStatus']], function () {

        //dashboard
        Route::get('/', function () {
            return redirect()->route('dashboard');
        });
        Route::group(['prefix' => 'dashboard'], function () {
            Route::get('/', 'DashboardController@index')->name('dashboard');
        });
        +
        //ADMINISTRACIÓN
        Route::group(['prefix' => 'administration'], function () {

            //USUARIOS
            Route::group(['prefix' => 'users'], function () {
                Route::get('/', 'UserController@index')->name('users.index')->middleware('ability:admin,a-users-query|a-users-create|a-users-show|a-users-update|a-users-destroy');
                Route::get('/{role}/create', 'UserController@create')->name('users.create')->middleware('ability:admin,a-users-create');
                Route::post('/{role}/store', 'UserController@store')->name('users.store')->middleware('ability:admin,a-users-create');
                Route::get('/{user}/show', 'UserController@show')->name('users.show')->middleware('ability:admin,a-users-show');
                Route::get('/{user}/edit', 'UserController@edit')->name('users.edit')->middleware('ability:admin,a-users-update');
                Route::put('/{user}/update', 'UserController@update')->name('users.update')->middleware('ability:admin,a-users-update');
                Route::delete('/{user}', 'UserController@destroy')->name('users.destroy')->middleware('ability:admin,a-users-destroy');
            });

            //PERMISOS
            Route::group(['prefix' => 'permissions'], function () {
                Route::get('/', 'PermissionController@index')->name('admin.permission-index')->middleware('ability:admin,a-permissions-query|a-permissions-create|a-permissions-update|a-permissions-destroy');
                Route::get('/create', 'PermissionController@create')->name('admin.permission-create')->middleware('ability:admin,a-permissions-create');
                Route::post('/store', 'PermissionController@store')->name('admin.permission-store')->middleware('ability:admin,a-permissions-create');
                Route::get('/{permission}/edit', 'PermissionController@edit')->name('admin.permission-edit')->middleware('ability:admin,a-permissions-update');
                Route::put('/{permission}/update', 'PermissionController@update')->name('admin.permission-update')->middleware('ability:admin,a-permissions-update');
                Route::delete('/{permission}', 'PermissionController@destroy')->name('admin.permission-destroy')->middleware('ability:admin,a-permissions-destroy');
            });

            //ROLES
            Route::group(['prefix' => 'roles'], function () {
                Route::get('/', 'RoleController@index')->name('roles-index')->middleware('ability:admin,a-roles-query|a-roles-create|a-roles-update|a-roles-show');
                Route::get('/create', 'RoleController@create')->name('roles-create')->middleware('ability:admin,a-roles-create');
                Route::post('/store', 'RoleController@store')->name('roles-store')->middleware('ability:admin,a-roles-create');
                Route::get('/{role}/show', 'RoleController@show')->name('roles-show')->middleware('ability:admin,a-roles-show');
                Route::get('/{role}/edit', 'RoleController@edit')->name('roles-edit')->middleware('ability:admin,a-roles-update');
                Route::put('/{role}/update', 'RoleController@update')->name('roles-update')->middleware('ability:admin,a-roles-update');
                Route::delete('/{role}', 'RoleController@destroy')->name('roles-destroy')->middleware('ability:admin,a-roles-destroy');
            });

        });

        //LOGS
        Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

    });
});


Route::group(['prefix' => 'email'], function () {
    Route::get('inbox', function () {
        return view('pages.email.inbox');
    });
    Route::get('read', function () {
        return view('pages.email.read');
    });
    Route::get('compose', function () {
        return view('pages.email.compose');
    });
});

Route::group(['prefix' => 'apps'], function () {
    Route::get('chat', function () {
        return view('pages.apps.chat');
    });
    Route::get('calendar', function () {
        return view('pages.apps.calendar');
    });
});

Route::group(['prefix' => 'ui-components'], function () {
    Route::get('alerts', function () {
        return view('pages.ui-components.alerts');
    });
    Route::get('badges', function () {
        return view('pages.ui-components.badges');
    });
    Route::get('breadcrumbs', function () {
        return view('pages.ui-components.breadcrumbs');
    });
    Route::get('buttons', function () {
        return view('pages.ui-components.buttons');
    });
    Route::get('button-group', function () {
        return view('pages.ui-components.button-group');
    });
    Route::get('cards', function () {
        return view('pages.ui-components.cards');
    });
    Route::get('carousel', function () {
        return view('pages.ui-components.carousel');
    });
    Route::get('collapse', function () {
        return view('pages.ui-components.collapse');
    });
    Route::get('dropdowns', function () {
        return view('pages.ui-components.dropdowns');
    });
    Route::get('list-group', function () {
        return view('pages.ui-components.list-group');
    });
    Route::get('media-object', function () {
        return view('pages.ui-components.media-object');
    });
    Route::get('modal', function () {
        return view('pages.ui-components.modal');
    });
    Route::get('navs', function () {
        return view('pages.ui-components.navs');
    });
    Route::get('navbar', function () {
        return view('pages.ui-components.navbar');
    });
    Route::get('pagination', function () {
        return view('pages.ui-components.pagination');
    });
    Route::get('popovers', function () {
        return view('pages.ui-components.popovers');
    });
    Route::get('progress', function () {
        return view('pages.ui-components.progress');
    });
    Route::get('scrollbar', function () {
        return view('pages.ui-components.scrollbar');
    });
    Route::get('scrollspy', function () {
        return view('pages.ui-components.scrollspy');
    });
    Route::get('spinners', function () {
        return view('pages.ui-components.spinners');
    });
    Route::get('tabs', function () {
        return view('pages.ui-components.tabs');
    });
    Route::get('tooltips', function () {
        return view('pages.ui-components.tooltips');
    });
});

Route::group(['prefix' => 'advanced-ui'], function () {
    Route::get('cropper', function () {
        return view('pages.advanced-ui.cropper');
    });
    Route::get('owl-carousel', function () {
        return view('pages.advanced-ui.owl-carousel');
    });
    Route::get('sweet-alert', function () {
        return view('pages.advanced-ui.sweet-alert');
    });
});

Route::group(['prefix' => 'forms'], function () {
    Route::get('basic-elements', function () {
        return view('pages.forms.basic-elements');
    });
    Route::get('advanced-elements', function () {
        return view('pages.forms.advanced-elements');
    });
    Route::get('editors', function () {
        return view('pages.forms.editors');
    });
    Route::get('wizard', function () {
        return view('pages.forms.wizard');
    });
});

Route::group(['prefix' => 'charts'], function () {
    Route::get('apex', function () {
        return view('pages.charts.apex');
    });
    Route::get('chartjs', function () {
        return view('pages.charts.chartjs');
    });
    Route::get('flot', function () {
        return view('pages.charts.flot');
    });
    Route::get('morrisjs', function () {
        return view('pages.charts.morrisjs');
    });
    Route::get('peity', function () {
        return view('pages.charts.peity');
    });
    Route::get('sparkline', function () {
        return view('pages.charts.sparkline');
    });
});

Route::group(['prefix' => 'tables'], function () {
    Route::get('basic-tables', function () {
        return view('pages.tables.basic-tables');
    });
    Route::get('data-table', function () {
        return view('pages.tables.data-table');
    });
});

Route::group(['prefix' => 'icons'], function () {
    Route::get('feather-icons', function () {
        return view('pages.icons.feather-icons');
    });
    Route::get('flag-icons', function () {

app/User.php
<?php
/**
 * Copyright (c) 2020. All Rights Reserved
 * Trébol Colombia SAS - www.trebolcolombia.com
 * Written by Jonathan Torres <jonathan8312 at gmail.com>
 */

namespace App;

use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Trebol\Entrust\Traits\EntrustUserTrait;

class User extends Authenticatable
{
    use Notifiable, EntrustUserTrait{
        EntrustUserTrait::restore as entrust_restore;
    }


    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'document', 'name', 'email', 'email_verified_at', 'password', 'mobile', 'address', 'active', 'privacy_policy'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function restore()
    {
        $result = $this->soft_delete_restore();
        $this->entrust_restore();
        return $result;
    }

    public function scopeSearch($query, $search_term)
    {
        $query->where('name', 'like', '%' . $search_term . '%')
            ->orWhere('email', 'like', '%' . $search_term . '%')
            ->orWhere('document', 'like', '%' . $search_term . '%');
    }

    //ESTADO DEL USUARIO
    public function getStatusLabelAttribute()
    {
        switch ($this->active) {
            case true:
                return '<span class="badge badge-outlinesuccess" style="font-size: 100%;"><strong>ACEPTADO</strong></span>';
            case false:
                return '<span class="badge badge-outlinedanger" style="font-size: 100%;"><strong>PENDIENTE</strong></span>';
            default:
                return '<span class="badge badge-outlinedanger" style="font-size: 100%;"><strong>' . $this->public . '</strong></span>';
        }
    }

    //POLITICA DE PRIVACIDAD
    public function getPrivacityLabelAttribute()
    {
        switch ($this->privacy_policy) {
            case true:
                return '<span class="badge badge-outlinesuccess" style="font-size: 100%;"><strong>SI</strong></span>';
            case false:
                return '<span class="badge badge-outlinedanger" style="font-size: 100%;"><strong>NO</strong></span>';
            default:
                return '<span class="badge badge-outlinedanger" style="font-size: 100%;"><strong>' . $this->privacy_policy . '</strong></span>';
        }
    }
}

resources/views/users/create.blade.php
@extends('layout.master')

@section('content')
    <nav class="page-breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{ route('dashboard') }}">Tablero de control</a></li>
            <li class="breadcrumb-item" aria-current="page">Administración</li>
            <li class="breadcrumb-item" aria-current="page">Usuarios</li>
            <li class="breadcrumb-item" aria-current="page">Listado de usuarios</li>
            <li class="breadcrumb-item active" aria-current="page">Nuevo</li>
        </ol>
    </nav>
    <div class="card">
        <div class="card-header">
            <strong class="text-uppercase">Nuevo usuario {{$role->display_name}}</strong>
        </div>
        <form action="{{ route('users.store', $role)}}" method="POST" autocomplete="off">
            @csrf
            <div class="card-body">
                <div class="row">
                    <div class="col-md-3">
                        <div class="form-group">
                            <label for="name"><strong>Nombre <span class="text-danger">*</span>
                                </strong></label>
                            <input id="name" class="form-control" type="text" name="name" required
                                   value="{{old('name')}}">
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="form-group">
                            <label for="email"><strong>Correo electrónico <span class="text-danger">*</span></strong></label>
                            <input id="email" class="form-control" type="text" name="email"
                                   data-inputmask="'alias': 'email'" required value="{{old('email')}}">
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="form-group">
                            <label for="document "><strong>Número de documento <span class="text-danger">*</span></strong></label>
                            <input id="document" class="form-control" type="text" name="document"
                                   data-inputmask-alias="9999999999" value="{{old('document')}}" required>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="form-group">
                            <label for="mobile"><strong>Dirección <span class="text-danger">*</span></strong></label>
                            <input id="text" class="form-control" type="text" name="address"
                                   value="{{old('address')}}" required>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="password"><strong>Contraseña <span class="text-danger">*</span></strong></label>
                            <input id="password" class="form-control" type="password" name="password" required>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="password_confirmation"><strong>Confirmar contraseña <span
                                        class="text-danger">*</span></strong></label>
                            <input id="password_confirmation" class="form-control" type="password"
                                   name="password_confirmation" required>
                        </div>
                    </div>
                </div>
            </div>
            <div class="card-footer">
                <a class="btn btn-primary" href="{{ route ('users.index')}}" role="button">
                    Volver
                </a>
                <button type="submit" class="btn btn-success updated">
                    Guardar
                </button>
            </div>
        </form>
    </div>
@endsection

resources/views/users/index.blade.php
@extends('layout.master')

@section('content')
    <nav class="page-breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{ route('dashboard') }}">Tablero de control</a></li>
            <li class="breadcrumb-item" aria-current="page">Administración</li>
            <li class="breadcrumb-item" aria-current="page">Usuarios</li>
            <li class="breadcrumb-item active" aria-current="page">Listado de usuarios</li>
        </ol>
    </nav>
    <div class="card text-center">
        <div class="card-header">
            <ul class="nav nav-tabs" id="myTab" role="tablist">
                @foreach($roles as $role)
                    <li class="nav-item">
                        <a class="nav-link {{count(request()->all()) ? (array_key_exists('search-'.$role->name,request()->all()) ? 'active':''): ($loop->first ? 'active':'')}}"
                           id="{{$role->name}}-tab" data-toggle="tab" href="#{{$role->name}}" role="tab"
                           aria-controls="{{$role->name}}" aria-selected="true">{{$role->display_name}}</a>
                    </li>
                @endforeach
            </ul>
        </div>
        <div class="card-body">
            <div class="tab-content" id="myTabContent">
                @foreach($roles as $role)
                    <div
                        class="tab-pane fade {{count(request()->all()) ? (array_key_exists('search-'.$role->name,request()->all()) ? 'show active':''): ($loop->first ? 'show active':'')}}"
                        id="{{$role->name}}" role="tabpanel" aria-labelledby="{{$role->name}}-tab">
                        <br>
                        <div class="row">
                            <div class="col-md-6 text-left">
                                @ability('admin','a-users-create')
                                <a href="{{route('users.create', $role)}}" class="btn btn-outline-primary float-left">
                                    <span class="link-title">
                                        Nuevo usuario
                                    </span>
                                </a>
                                @endability

                            </div>
                            <div class="col-md-6">
                                <form class="form-inline my-2 my-lg-0">
                                    <input type="text" name="search-{{$role->name}}"
                                           value="{{request()->input('search-'.$role->name)}}"
                                           class="form-control mr-sm-2" style="width: 64%" autofocus="autofocus"
                                           placeholder="Ingrese el nombre del {{$role->display_name}} a buscar">
                                    <button class="btn btn-outline-primary">
                                        Buscar
                                    </button>
                                    &nbsp;
                                    <a href="{{route('users.index')}}" class="btn btn-outline-primary">Limpiar</a>
                                </form>
                            </div>
                        </div>
                        <br>
                        <div class="table-responsive" id="table-{{$role->name}}">
                            <table id="orders-table" class="table table-bordered table-sm table-hover table-condensed">
                                <thead>
                                <tr class="bg-primary">
                                    <th class="text-center text-white">Número de documento</th>
                                    <th class="text-center text-white">Nombre</th>
                                    <th class="text-center text-white">Correo electrónico</th>
                                    <th class="text-center text-white">Número de teléfono</th>
                                    <th class="text-center text-white">Estado del usuario</th>
                                    @ability('admin','a-users-update,a-users-destroy')
                                    <th class="text-center text-white">Opciones</th>
                                    @endability
                                </tr>
                                </thead>
                                <tbody>
                                @foreach ($users[$role->name] as $user)
                                    <tr>
                                        <td style="text-align: left !important;">{{$user->document}}</td>
                                        <td style="text-align: left !important;">{{$user->name}}</td>
                                        <td style="text-align: left !important;">{{$user->email}}</td>
                                        <td style="text-align: center !important;">{{$user->mobile}}</td>
                                        <td class="text-center">{!! $user->status_label !!}</td>
                                        @if ($role->name == 'admin')
                                            @ability('admin','a-users-update,a-users-show,a-users-destroy')
                                            <td class="text-center" width="120px">
                                                <div class="btn-group">
                                                    @if(auth()->user()->hasRole('admin'))
                                                        @ability('admin','a-users-update')
                                                        <a href="{{ route ('users.edit', $user) }}"
                                                           title="Ver">
                                                            <i class="link-icon text-warning"
                                                               data-feather="edit-2"></i>
                                                        </a>
                                                        @endability
                                                        &nbsp;
                                                        @ability('admin','a-users-destroy')
                                                        <form method="POST"
                                                              action="{{ route('users.destroy', $user)}}">
                                                            @csrf
                                                            @method('delete')
                                                            <span class="destroy btn-trash"
                                                                  title="Eliminar">
                                                                <i class="link-icon text-danger"
                                                                   data-feather="trash-2"></i></span>
                                                        </form>
                                                        @endability
                                                    @else
                                                        @if($user->id == $auth)
                                                            @ability('admin','a-users-update')
                                                            <a href="{{ route ('users.edit', $user) }}"
                                                               title="Editar">
                                                                <i class="link-icon text-warning"
                                                                   data-feather="edit-2"></i>
                                                            </a>
                                                            @endability
                                                        @endif
                                                    @endif
                                                </div>
                                            </td>
                                            @endability
                                        @endif
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                            <br>
                            {{$users[$role->name]->appends(request()->all())->render()}}
                        </div>
                    </div>
                @endforeach

            </div>
        </div>
    </div>
@endsection

@push('custom-scripts')
    <script>
        $(document).ready(function () {
            $(document).on('click', '.pagination a', function (event) {
                event.preventDefault();
                $(this).parent().find('li .active').removeClass('active');
                $(this).parent('li').addClass('active');
                var $element = $(this).parent().parent().parent();
                if (!$element.prop('id'))
                    $element = $element.parent();

                var page = $(this).prop('href').split('page=')[1];
                var tab = 'search-' + ($element.prop('id').replace('table-', ''));

                console.log($.urlParam(tab));
                if ($.urlParam(tab) == null || $.urlParam(tab) == 0)
                    window.location.href = window.location.href.split('?')[0] + `?${tab}=&page=${page}`;
                else
                    window.location.href = window.location.href.split('?')[0] + `?${tab}=${$.urlParam(tab)}&page=${page}`;
            });

        });


        $.urlParam = function (name) {
            var results = new RegExp('[\?&]' + name + '=([^&#]*)').exec(window.location.href);
            if (results == null) {
                return null;
            }
            return decodeURI(results[1]) || 0;
        }
    </script>
@endpush